[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NETLIFY_NEXT_VERIFY_FORMS = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs" 